/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
	CsrfToken,
	MarkAnswerAsWrongRequest,
	MarkWordAsInvalidRequest,
	Options,
	Question,
	SendAnswerGermanWordRequest,
	SendAnswerPokemonNameRequest,
	SetOptionRequestRequest,
	WasAnswerCorrect,
	WasAnswerCorrectPokemonName
} from '../models/index';
import {
	CsrfTokenFromJSON,
	MarkAnswerAsWrongRequestToJSON,
	MarkWordAsInvalidRequestToJSON,
	OptionsFromJSON,
	QuestionFromJSON,
	SendAnswerGermanWordRequestToJSON,
	SendAnswerPokemonNameRequestToJSON,
	SetOptionRequestRequestToJSON,
	WasAnswerCorrectFromJSON,
	WasAnswerCorrectPokemonNameFromJSON
} from '../models/index';

export interface LearningApiMarkAnswerAsWrongCreateRequest {
	markAnswerAsWrongRequest: MarkAnswerAsWrongRequest;
}

export interface LearningApiMarkWordAsInvalidCreateRequest {
	markWordAsInvalidRequest: MarkWordAsInvalidRequest;
}

export interface LearningApiSendAnswerGermanWordCreateRequest {
	sendAnswerGermanWordRequest: SendAnswerGermanWordRequest;
}

export interface LearningApiSendAnswerPokemonNameCreateRequest {
	sendAnswerPokemonNameRequest: SendAnswerPokemonNameRequest;
}

export interface LearningApiSetOptionCreateRequest {
	setOptionRequestRequest: SetOptionRequestRequest;
}

/**
 *
 */
export class LearningApi extends runtime.BaseAPI {

	/**
	 */
	async learningApiGetCsrfTokenRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CsrfToken>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request({
			path: `/learning/api/get_csrf_token`,
			method: 'GET',
			headers: headerParameters,
			query: queryParameters
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => CsrfTokenFromJSON(jsonValue));
	}

	/**
	 */
	async learningApiGetCsrfTokenRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CsrfToken> {
		const response = await this.learningApiGetCsrfTokenRetrieveRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async learningApiGetNextQuestionRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Question>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request({
			path: `/learning/api/get_next_question/`,
			method: 'GET',
			headers: headerParameters,
			query: queryParameters
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => QuestionFromJSON(jsonValue));
	}

	/**
	 */
	async learningApiGetNextQuestionRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Question> {
		const response = await this.learningApiGetNextQuestionRetrieveRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async learningApiGetOptionsRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Options>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request({
			path: `/learning/api/get_options/`,
			method: 'GET',
			headers: headerParameters,
			query: queryParameters
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => OptionsFromJSON(jsonValue));
	}

	/**
	 */
	async learningApiGetOptionsRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Options> {
		const response = await this.learningApiGetOptionsRetrieveRaw(initOverrides);
		return await response.value();
	}

	/**
	 */
	async learningApiMarkAnswerAsWrongCreateRaw(requestParameters: LearningApiMarkAnswerAsWrongCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['markAnswerAsWrongRequest'] == null) {
			throw new runtime.RequiredError(
				'markAnswerAsWrongRequest',
				'Required parameter "markAnswerAsWrongRequest" was null or undefined when calling learningApiMarkAnswerAsWrongCreate().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request({
			path: `/learning/api/mark_answer_as_wrong/`,
			method: 'POST',
			headers: headerParameters,
			query: queryParameters,
			body: MarkAnswerAsWrongRequestToJSON(requestParameters['markAnswerAsWrongRequest'])
		}, initOverrides);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async learningApiMarkAnswerAsWrongCreate(requestParameters: LearningApiMarkAnswerAsWrongCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
		await this.learningApiMarkAnswerAsWrongCreateRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async learningApiMarkWordAsInvalidCreateRaw(requestParameters: LearningApiMarkWordAsInvalidCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['markWordAsInvalidRequest'] == null) {
			throw new runtime.RequiredError(
				'markWordAsInvalidRequest',
				'Required parameter "markWordAsInvalidRequest" was null or undefined when calling learningApiMarkWordAsInvalidCreate().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request({
			path: `/learning/api/mark_word_as_invalid/`,
			method: 'POST',
			headers: headerParameters,
			query: queryParameters,
			body: MarkWordAsInvalidRequestToJSON(requestParameters['markWordAsInvalidRequest'])
		}, initOverrides);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async learningApiMarkWordAsInvalidCreate(requestParameters: LearningApiMarkWordAsInvalidCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
		await this.learningApiMarkWordAsInvalidCreateRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async learningApiSendAnswerGermanWordCreateRaw(requestParameters: LearningApiSendAnswerGermanWordCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasAnswerCorrect>> {
		if (requestParameters['sendAnswerGermanWordRequest'] == null) {
			throw new runtime.RequiredError(
				'sendAnswerGermanWordRequest',
				'Required parameter "sendAnswerGermanWordRequest" was null or undefined when calling learningApiSendAnswerGermanWordCreate().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request({
			path: `/learning/api/send_answer_german_word/`,
			method: 'POST',
			headers: headerParameters,
			query: queryParameters,
			body: SendAnswerGermanWordRequestToJSON(requestParameters['sendAnswerGermanWordRequest'])
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => WasAnswerCorrectFromJSON(jsonValue));
	}

	/**
	 */
	async learningApiSendAnswerGermanWordCreate(requestParameters: LearningApiSendAnswerGermanWordCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasAnswerCorrect> {
		const response = await this.learningApiSendAnswerGermanWordCreateRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async learningApiSendAnswerPokemonNameCreateRaw(requestParameters: LearningApiSendAnswerPokemonNameCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasAnswerCorrectPokemonName>> {
		if (requestParameters['sendAnswerPokemonNameRequest'] == null) {
			throw new runtime.RequiredError(
				'sendAnswerPokemonNameRequest',
				'Required parameter "sendAnswerPokemonNameRequest" was null or undefined when calling learningApiSendAnswerPokemonNameCreate().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request({
			path: `/learning/api/send_answer_pokemon_name/`,
			method: 'POST',
			headers: headerParameters,
			query: queryParameters,
			body: SendAnswerPokemonNameRequestToJSON(requestParameters['sendAnswerPokemonNameRequest'])
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => WasAnswerCorrectPokemonNameFromJSON(jsonValue));
	}

	/**
	 */
	async learningApiSendAnswerPokemonNameCreate(requestParameters: LearningApiSendAnswerPokemonNameCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasAnswerCorrectPokemonName> {
		const response = await this.learningApiSendAnswerPokemonNameCreateRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async learningApiSetOptionCreateRaw(requestParameters: LearningApiSetOptionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['setOptionRequestRequest'] == null) {
			throw new runtime.RequiredError(
				'setOptionRequestRequest',
				'Required parameter "setOptionRequestRequest" was null or undefined when calling learningApiSetOptionCreate().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request({
			path: `/learning/api/set_option/`,
			method: 'POST',
			headers: headerParameters,
			query: queryParameters,
			body: SetOptionRequestRequestToJSON(requestParameters['setOptionRequestRequest'])
		}, initOverrides);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async learningApiSetOptionCreate(requestParameters: LearningApiSetOptionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
		await this.learningApiSetOptionCreateRaw(requestParameters, initOverrides);
	}

}
