openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /learning/api/get_csrf_token:
    get:
      operationId: learning_api_get_csrf_token_retrieve
      tags:
        - learning
      security:
        - cookieAuth: [ ]
        - { }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CsrfToken'
          description: ''
  /learning/api/get_next_question/:
    get:
      operationId: learning_api_get_next_question_retrieve
      tags:
        - learning
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
          description: ''
  /learning/api/mark_answer_as_wrong/:
    post:
      operationId: learning_api_mark_answer_as_wrong_create
      tags:
        - learning
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkAnswerAsWrongRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MarkAnswerAsWrongRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MarkAnswerAsWrongRequest'
        required: true
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: No response body
  /learning/api/mark_word_as_invalid/:
    post:
      operationId: learning_api_mark_word_as_invalid_create
      tags:
        - learning
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkWordAsInvalidRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MarkWordAsInvalidRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MarkWordAsInvalidRequest'
        required: true
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: No response body
  /learning/api/send_answer_german_word/:
    post:
      operationId: learning_api_send_answer_german_word_create
      tags:
        - learning
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendAnswerGermanWordRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendAnswerGermanWordRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SendAnswerGermanWordRequest'
        required: true
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WasAnswerCorrect'
          description: ''
  /learning/api/send_answer_pokemon_name/:
    post:
      operationId: learning_api_send_answer_pokemon_name_create
      tags:
        - learning
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendAnswerPokemonNameRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendAnswerPokemonNameRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SendAnswerPokemonNameRequest'
        required: true
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WasAnswerCorrectPokemonName'
          description: ''
components:
  schemas:
    CsrfToken:
      type: object
      properties:
        csrf_token:
          type: string
      required:
        - csrf_token
    GermanWordQuestionContent:
      type: object
      properties:
        word:
          $ref: '#/components/schemas/Word'
        rank:
          type: integer
      required:
        - rank
        - word
    MarkAnswerAsWrongRequest:
      type: object
      properties:
        word_id:
          type: integer
      required:
        - word_id
    MarkWordAsInvalidRequest:
      type: object
      properties:
        word_id:
          type: integer
      required:
        - word_id
    PokemonNameQuestionContent:
      type: object
      properties:
        pokemon_id:
          type: integer
        given_name:
          type: string
        given_language_id:
          type: integer
        given_language_name:
          type: string
        expected_name:
          type: string
        expected_language_id:
          type: integer
        expected_language_name:
          type: string
      required:
        - expected_language_id
        - expected_language_name
        - expected_name
        - given_language_id
        - given_language_name
        - given_name
        - pokemon_id
    Question:
      type: object
      properties:
        question_type:
          $ref: '#/components/schemas/QuestionTypeEnum'
        german_word_content:
          allOf:
            - $ref: '#/components/schemas/GermanWordQuestionContent'
          nullable: true
        pokemon_name_content:
          allOf:
            - $ref: '#/components/schemas/PokemonNameQuestionContent'
          nullable: true
        stats:
          $ref: '#/components/schemas/QuestionStats'
      required:
        - german_word_content
        - pokemon_name_content
        - question_type
        - stats
    QuestionStats:
      type: object
      properties:
        nb_answers_total:
          type: integer
        nb_answers_correct:
          type: integer
        nb_answers_correct_in_a_row:
          type: integer
      required:
        - nb_answers_correct
        - nb_answers_correct_in_a_row
        - nb_answers_total
    QuestionTypeEnum:
      enum:
        - pokemon_name
        - german_word
      type: string
      description: |-
        * `pokemon_name` - pokemon_name
        * `german_word` - german_word
    SendAnswerGermanWordRequest:
      type: object
      properties:
        word_id:
          type: integer
        answer:
          type: string
          minLength: 1
      required:
        - answer
        - word_id
    SendAnswerPokemonNameRequest:
      type: object
      properties:
        pokemon_id:
          type: integer
        answer:
          type: string
          minLength: 1
        expected_language_id:
          type: integer
        given_language_id:
          type: integer
      required:
        - answer
        - expected_language_id
        - given_language_id
        - pokemon_id
    TypeEnum:
      enum:
        - noun
        - verb
        - adjective
      type: string
      description: |-
        * `noun` - Noun
        * `verb` - Verb
        * `adjective` - Adjective
    WasAnswerCorrect:
      type: object
      properties:
        correct:
          type: boolean
        learned:
          type: boolean
        nb_answers_correct_in_a_row:
          type: integer
        repetitions_to_learn:
          type: integer
      required:
        - correct
        - learned
        - nb_answers_correct_in_a_row
        - repetitions_to_learn
    WasAnswerCorrectPokemonName:
      type: object
      properties:
        was_correct_given_language:
          allOf:
            - $ref: '#/components/schemas/WasAnswerCorrect'
          nullable: true
        was_correct_expected_language:
          $ref: '#/components/schemas/WasAnswerCorrect'
      required:
        - was_correct_expected_language
        - was_correct_given_language
    Word:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        word:
          type: string
          maxLength: 100
        type:
          $ref: '#/components/schemas/TypeEnum'
        gender:
          type: string
          nullable: true
          maxLength: 10
        usage_frequency:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
        - id
        - type
        - usage_frequency
        - word
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
