/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
	ConfigurationResponse
} from '../models/index';
import {
	ConfigurationResponseFromJSON,
	ConfigurationResponseToJSON
} from '../models/index';

export interface AllauthClientV1ConfigGetRequest {
	client: AllauthClientV1ConfigGetClientEnum;
}

/**
 * 
 */
export class ConfigurationApi extends runtime.BaseAPI {

	/**
	 * There are many configuration options that alter the functionality and behavior of django-allauth, some of which can also impact the frontend. Therefore, relevant configuration options are exposed via this endpoint. The data returned is not user/authentication dependent. Hence, it suffices to only fetch this data once at boot time of your application.
	 * Get configuration
	 */
	async allauthClientV1ConfigGetRaw(requestParameters: AllauthClientV1ConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigurationResponse>> {
		if (requestParameters['client'] == null) {
			throw new runtime.RequiredError(
				'client',
				'Required parameter "client" was null or undefined when calling allauthClientV1ConfigGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request({
			path: `/_allauth/{client}/v1/config`.replace(`{${'client'}}`, encodeURIComponent(String(requestParameters['client']))),
			method: 'GET',
			headers: headerParameters,
			query: queryParameters
		}, initOverrides);

		return new runtime.JSONApiResponse(response, (jsonValue) => ConfigurationResponseFromJSON(jsonValue));
	}

	/**
	 * There are many configuration options that alter the functionality and behavior of django-allauth, some of which can also impact the frontend. Therefore, relevant configuration options are exposed via this endpoint. The data returned is not user/authentication dependent. Hence, it suffices to only fetch this data once at boot time of your application.
	 * Get configuration
	 */
	async allauthClientV1ConfigGet(requestParameters: AllauthClientV1ConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigurationResponse> {
		const response = await this.allauthClientV1ConfigGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

}

/**
 * @export
 */
export const AllauthClientV1ConfigGetClientEnum = {
	App: 'app',
	Browser: 'browser'
} as const;
export type AllauthClientV1ConfigGetClientEnum = typeof AllauthClientV1ConfigGetClientEnum[keyof typeof AllauthClientV1ConfigGetClientEnum];
