/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CsrfToken
 */
export interface CsrfToken {
	/**
	 *
	 * @type {string}
	 * @memberof CsrfToken
	 */
	csrfToken: string;
}

/**
 * Check if a given object implements the CsrfToken interface.
 */
export function instanceOfCsrfToken(value: object): value is CsrfToken {
	if (!('csrfToken' in value) || value['csrfToken'] === undefined) return false;
	return true;
}

export function CsrfTokenFromJSON(json: any): CsrfToken {
	return CsrfTokenFromJSONTyped(json, false);
}

export function CsrfTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsrfToken {
	if (json == null) {
		return json;
	}
	return {

		'csrfToken': json['csrf_token']
	};
}

export function CsrfTokenToJSON(value?: CsrfToken | null): any {
	if (value == null) {
		return value;
	}
	return {

		'csrf_token': value['csrfToken']
	};
}

