/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Word } from './Word';
import { WordFromJSON, WordToJSON } from './Word';

/**
 *
 * @export
 * @interface GermanWordQuestionContent
 */
export interface GermanWordQuestionContent {
	/**
	 *
	 * @type {Word}
	 * @memberof GermanWordQuestionContent
	 */
	word: Word;
	/**
	 *
	 * @type {number}
	 * @memberof GermanWordQuestionContent
	 */
	rank: number;
}

/**
 * Check if a given object implements the GermanWordQuestionContent interface.
 */
export function instanceOfGermanWordQuestionContent(value: object): value is GermanWordQuestionContent {
	if (!('word' in value) || value['word'] === undefined) return false;
	if (!('rank' in value) || value['rank'] === undefined) return false;
	return true;
}

export function GermanWordQuestionContentFromJSON(json: any): GermanWordQuestionContent {
	return GermanWordQuestionContentFromJSONTyped(json, false);
}

export function GermanWordQuestionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GermanWordQuestionContent {
	if (json == null) {
		return json;
	}
	return {

		'word': WordFromJSON(json['word']),
		'rank': json['rank']
	};
}

export function GermanWordQuestionContentToJSON(value?: GermanWordQuestionContent | null): any {
	if (value == null) {
		return value;
	}
	return {

		'word': WordToJSON(value['word']),
		'rank': value['rank']
	};
}

