/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Word } from './Word';
import { WordFromJSON, WordToJSON } from './Word';

/**
 *
 * @export
 * @interface GetNextWord
 */
export interface GetNextWord {
	/**
	 *
	 * @type {Word}
	 * @memberof GetNextWord
	 */
	word: Word;
	/**
	 *
	 * @type {number}
	 * @memberof GetNextWord
	 */
	rank: number;
	/**
	 *
	 * @type {number}
	 * @memberof GetNextWord
	 */
	nbAnswersTotal: number;
	/**
	 *
	 * @type {number}
	 * @memberof GetNextWord
	 */
	nbAnswersCorrect: number;
	/**
	 *
	 * @type {number}
	 * @memberof GetNextWord
	 */
	nbAnswersCorrectInARow: number;
}

/**
 * Check if a given object implements the GetNextWord interface.
 */
export function instanceOfGetNextWord(value: object): value is GetNextWord {
	if (!('word' in value) || value['word'] === undefined) return false;
	if (!('rank' in value) || value['rank'] === undefined) return false;
	if (!('nbAnswersTotal' in value) || value['nbAnswersTotal'] === undefined) return false;
	if (!('nbAnswersCorrect' in value) || value['nbAnswersCorrect'] === undefined) return false;
	if (!('nbAnswersCorrectInARow' in value) || value['nbAnswersCorrectInARow'] === undefined) return false;
	return true;
}

export function GetNextWordFromJSON(json: any): GetNextWord {
	return GetNextWordFromJSONTyped(json, false);
}

export function GetNextWordFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNextWord {
	if (json == null) {
		return json;
	}
	return {

		'word': WordFromJSON(json['word']),
		'rank': json['rank'],
		'nbAnswersTotal': json['nb_answers_total'],
		'nbAnswersCorrect': json['nb_answers_correct'],
		'nbAnswersCorrectInARow': json['nb_answers_correct_in_a_row']
	};
}

export function GetNextWordToJSON(value?: GetNextWord | null): any {
	if (value == null) {
		return value;
	}
	return {

		'word': WordToJSON(value['word']),
		'rank': value['rank'],
		'nb_answers_total': value['nbAnswersTotal'],
		'nb_answers_correct': value['nbAnswersCorrect'],
		'nb_answers_correct_in_a_row': value['nbAnswersCorrectInARow']
	};
}

