/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarkAnswerAsWrongRequest
 */
export interface MarkAnswerAsWrongRequest {
	/**
	 *
	 * @type {number}
	 * @memberof MarkAnswerAsWrongRequest
	 */
	wordId: number;
}

/**
 * Check if a given object implements the MarkAnswerAsWrongRequest interface.
 */
export function instanceOfMarkAnswerAsWrongRequest(value: object): value is MarkAnswerAsWrongRequest {
	if (!('wordId' in value) || value['wordId'] === undefined) return false;
	return true;
}

export function MarkAnswerAsWrongRequestFromJSON(json: any): MarkAnswerAsWrongRequest {
	return MarkAnswerAsWrongRequestFromJSONTyped(json, false);
}

export function MarkAnswerAsWrongRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAnswerAsWrongRequest {
	if (json == null) {
		return json;
	}
	return {

		'wordId': json['word_id']
	};
}

export function MarkAnswerAsWrongRequestToJSON(value?: MarkAnswerAsWrongRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'word_id': value['wordId']
	};
}

