/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Option
 */
export interface Option {
	/**
	 *
	 * @type {string}
	 * @memberof Option
	 */
	key: string;
	/**
	 *
	 * @type {string}
	 * @memberof Option
	 */
	displayName: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof Option
	 */
	enabled: boolean;
}

/**
 * Check if a given object implements the Option interface.
 */
export function instanceOfOption(value: object): value is Option {
	if (!('key' in value) || value['key'] === undefined) return false;
	if (!('displayName' in value) || value['displayName'] === undefined) return false;
	if (!('enabled' in value) || value['enabled'] === undefined) return false;
	return true;
}

export function OptionFromJSON(json: any): Option {
	return OptionFromJSONTyped(json, false);
}

export function OptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Option {
	if (json == null) {
		return json;
	}
	return {

		'key': json['key'],
		'displayName': json['display_name'],
		'enabled': json['enabled']
	};
}

export function OptionToJSON(value?: Option | null): any {
	if (value == null) {
		return value;
	}
	return {

		'key': value['key'],
		'display_name': value['displayName'],
		'enabled': value['enabled']
	};
}

