/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OptionGroup } from './OptionGroup';
import { OptionGroupFromJSON, OptionGroupToJSON } from './OptionGroup';

/**
 *
 * @export
 * @interface Options
 */
export interface Options {
	/**
	 *
	 * @type {Array<OptionGroup>}
	 * @memberof Options
	 */
	groups: Array<OptionGroup>;
}

/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): value is Options {
	if (!('groups' in value) || value['groups'] === undefined) return false;
	return true;
}

export function OptionsFromJSON(json: any): Options {
	return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
	if (json == null) {
		return json;
	}
	return {

		'groups': ((json['groups'] as Array<any>).map(OptionGroupFromJSON))
	};
}

export function OptionsToJSON(value?: Options | null): any {
	if (value == null) {
		return value;
	}
	return {

		'groups': ((value['groups'] as Array<any>).map(OptionGroupToJSON))
	};
}

