/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pokemon_name` - pokemon_name
 * * `german_word` - german_word
 * @export
 */
export const QuestionTypeEnum = {
    PokemonName: 'pokemon_name',
    GermanWord: 'german_word'
} as const;
export type QuestionTypeEnum = typeof QuestionTypeEnum[keyof typeof QuestionTypeEnum];


export function instanceOfQuestionTypeEnum(value: any): boolean {
    for (const key in QuestionTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(QuestionTypeEnum, key)) {
            if (QuestionTypeEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QuestionTypeEnumFromJSON(json: any): QuestionTypeEnum {
    return QuestionTypeEnumFromJSONTyped(json, false);
}

export function QuestionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionTypeEnum {
    return json as QuestionTypeEnum;
}

export function QuestionTypeEnumToJSON(value?: QuestionTypeEnum | null): any {
    return value as any;
}

