/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendAnswerGermanWordRequest
 */
export interface SendAnswerGermanWordRequest {
	/**
	 *
	 * @type {number}
	 * @memberof SendAnswerGermanWordRequest
	 */
	wordId: number;
	/**
	 *
	 * @type {string}
	 * @memberof SendAnswerGermanWordRequest
	 */
	answer: string;
}

/**
 * Check if a given object implements the SendAnswerGermanWordRequest interface.
 */
export function instanceOfSendAnswerGermanWordRequest(value: object): value is SendAnswerGermanWordRequest {
	if (!('wordId' in value) || value['wordId'] === undefined) return false;
	if (!('answer' in value) || value['answer'] === undefined) return false;
	return true;
}

export function SendAnswerGermanWordRequestFromJSON(json: any): SendAnswerGermanWordRequest {
	return SendAnswerGermanWordRequestFromJSONTyped(json, false);
}

export function SendAnswerGermanWordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendAnswerGermanWordRequest {
	if (json == null) {
		return json;
	}
	return {

		'wordId': json['word_id'],
		'answer': json['answer']
	};
}

export function SendAnswerGermanWordRequestToJSON(value?: SendAnswerGermanWordRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'word_id': value['wordId'],
		'answer': value['answer']
	};
}

