/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SendAnswerPokemonNameRequest
 */
export interface SendAnswerPokemonNameRequest {
	/**
	 *
	 * @type {number}
	 * @memberof SendAnswerPokemonNameRequest
	 */
	pokemonId: number;
	/**
	 *
	 * @type {string}
	 * @memberof SendAnswerPokemonNameRequest
	 */
	answer: string;
	/**
	 *
	 * @type {number}
	 * @memberof SendAnswerPokemonNameRequest
	 */
	expectedLanguageId: number;
	/**
	 *
	 * @type {number}
	 * @memberof SendAnswerPokemonNameRequest
	 */
	givenLanguageId: number;
}

/**
 * Check if a given object implements the SendAnswerPokemonNameRequest interface.
 */
export function instanceOfSendAnswerPokemonNameRequest(value: object): value is SendAnswerPokemonNameRequest {
	if (!('pokemonId' in value) || value['pokemonId'] === undefined) return false;
	if (!('answer' in value) || value['answer'] === undefined) return false;
	if (!('expectedLanguageId' in value) || value['expectedLanguageId'] === undefined) return false;
	if (!('givenLanguageId' in value) || value['givenLanguageId'] === undefined) return false;
	return true;
}

export function SendAnswerPokemonNameRequestFromJSON(json: any): SendAnswerPokemonNameRequest {
	return SendAnswerPokemonNameRequestFromJSONTyped(json, false);
}

export function SendAnswerPokemonNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendAnswerPokemonNameRequest {
	if (json == null) {
		return json;
	}
	return {

		'pokemonId': json['pokemon_id'],
		'answer': json['answer'],
		'expectedLanguageId': json['expected_language_id'],
		'givenLanguageId': json['given_language_id']
	};
}

export function SendAnswerPokemonNameRequestToJSON(value?: SendAnswerPokemonNameRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'pokemon_id': value['pokemonId'],
		'answer': value['answer'],
		'expected_language_id': value['expectedLanguageId'],
		'given_language_id': value['givenLanguageId']
	};
}

