/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SetOptionRequestRequest
 */
export interface SetOptionRequestRequest {
	/**
	 *
	 * @type {string}
	 * @memberof SetOptionRequestRequest
	 */
	optionKey: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof SetOptionRequestRequest
	 */
	enabled: boolean;
}

/**
 * Check if a given object implements the SetOptionRequestRequest interface.
 */
export function instanceOfSetOptionRequestRequest(value: object): value is SetOptionRequestRequest {
	if (!('optionKey' in value) || value['optionKey'] === undefined) return false;
	if (!('enabled' in value) || value['enabled'] === undefined) return false;
	return true;
}

export function SetOptionRequestRequestFromJSON(json: any): SetOptionRequestRequest {
	return SetOptionRequestRequestFromJSONTyped(json, false);
}

export function SetOptionRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetOptionRequestRequest {
	if (json == null) {
		return json;
	}
	return {

		'optionKey': json['option_key'],
		'enabled': json['enabled']
	};
}

export function SetOptionRequestRequestToJSON(value?: SetOptionRequestRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'option_key': value['optionKey'],
		'enabled': value['enabled']
	};
}

