# Generated by Django 5.1.4 on 2024-12-29 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_pokemon_generation"),
        ("pokemon_names", "0002_pokemonenabledgeneration_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pokemonenabledgeneration",
            constraint=models.UniqueConstraint(
                fields=("user", "generation"), name="unique_generation_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="pokemonenabledlanguage",
            constraint=models.UniqueConstraint(
                fields=("user", "language"), name="unique_language_per_user"
            ),
        ),
    ]
