/* tslint:disable */
/* eslint-disable */

/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SendAnswerRequest
 */
export interface SendAnswerRequest {
	/**
	 *
	 * @type {number}
	 * @memberof SendAnswerRequest
	 */
	wordId: number;
	/**
	 *
	 * @type {string}
	 * @memberof SendAnswerRequest
	 */
	answer: string;
}

/**
 * Check if a given object implements the SendAnswerRequest interface.
 */
export function instanceOfSendAnswerRequest(value: object): value is SendAnswerRequest {
	if (!('wordId' in value) || value['wordId'] === undefined) return false;
	if (!('answer' in value) || value['answer'] === undefined) return false;
	return true;
}

export function SendAnswerRequestFromJSON(json: any): SendAnswerRequest {
	return SendAnswerRequestFromJSONTyped(json, false);
}

export function SendAnswerRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SendAnswerRequest {
	if (json == null) {
		return json;
	}
	return {
		wordId: json['word_id'],
		answer: json['answer']
	};
}

export function SendAnswerRequestToJSON(value?: SendAnswerRequest | null): any {
	if (value == null) {
		return value;
	}
	return {
		word_id: value['wordId'],
		answer: value['answer']
	};
}
