/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `noun` - Noun
 * * `verb` - Verb
 * * `adjective` - Adjective
 * @export
 */
export const TypeEnum = {
	Noun: 'noun',
	Verb: 'verb',
	Adjective: 'adjective'
} as const;
export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

export function instanceOfTypeEnum(value: any): boolean {
	for (const key in TypeEnum) {
		if (Object.prototype.hasOwnProperty.call(TypeEnum, key)) {
			if (TypeEnum[key] === value) {
				return true;
			}
		}
	}
	return false;
}

export function TypeEnumFromJSON(json: any): TypeEnum {
	return TypeEnumFromJSONTyped(json, false);
}

export function TypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeEnum {
	return json as TypeEnum;
}

export function TypeEnumToJSON(value?: TypeEnum | null): any {
	return value as any;
}
