/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WasAnswerCorrect
 */
export interface WasAnswerCorrect {
	/**
	 *
	 * @type {boolean}
	 * @memberof WasAnswerCorrect
	 */
	correct: boolean;
}

/**
 * Check if a given object implements the WasAnswerCorrect interface.
 */
export function instanceOfWasAnswerCorrect(value: object): value is WasAnswerCorrect {
	if (!('correct' in value) || value['correct'] === undefined) return false;
	return true;
}

export function WasAnswerCorrectFromJSON(json: any): WasAnswerCorrect {
	return WasAnswerCorrectFromJSONTyped(json, false);
}

export function WasAnswerCorrectFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): WasAnswerCorrect {
	if (json == null) {
		return json;
	}
	return {
		correct: json['correct']
	};
}

export function WasAnswerCorrectToJSON(value?: WasAnswerCorrect | null): any {
	if (value == null) {
		return value;
	}
	return {

		'correct': value['correct',
	};
}

