/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration of the Django `allauth.account` app.
 * 
 * @export
 * @interface AccountConfiguration
 */
export interface AccountConfiguration {
	/**
	 *
	 * @type {string}
	 * @memberof AccountConfiguration
	 */
	authenticationMethod: AccountConfigurationAuthenticationMethodEnum;
	/**
	 *
	 * @type {boolean}
	 * @memberof AccountConfiguration
	 */
	isOpenForSignup: boolean;
}


/**
 * @export
 */
export const AccountConfigurationAuthenticationMethodEnum = {
	Email: 'email',
	Username: 'username',
	UsernameEmail: 'username_email'
} as const;
export type AccountConfigurationAuthenticationMethodEnum = typeof AccountConfigurationAuthenticationMethodEnum[keyof typeof AccountConfigurationAuthenticationMethodEnum];


/**
 * Check if a given object implements the AccountConfiguration interface.
 */
export function instanceOfAccountConfiguration(value: object): value is AccountConfiguration {
	if (!('authenticationMethod' in value) || value['authenticationMethod'] === undefined) return false;
	if (!('isOpenForSignup' in value) || value['isOpenForSignup'] === undefined) return false;
	return true;
}

export function AccountConfigurationFromJSON(json: any): AccountConfiguration {
	return AccountConfigurationFromJSONTyped(json, false);
}

export function AccountConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountConfiguration {
	if (json == null) {
		return json;
	}
	return {

		'authenticationMethod': json['authentication_method'],
		'isOpenForSignup': json['is_open_for_signup']
	};
}

export function AccountConfigurationToJSON(value?: AccountConfiguration | null): any {
	if (value == null) {
		return value;
	}
	return {

		'authentication_method': value['authenticationMethod'],
		'is_open_for_signup': value['isOpenForSignup']
	};
}

