/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StatusOK } from './StatusOK';
import { StatusOKFromJSON, StatusOKToJSON } from './StatusOK';

/**
 *
 * @export
 * @interface AllauthClientV1AuthPasswordRequestPost200Response
 */
export interface AllauthClientV1AuthPasswordRequestPost200Response {
	/**
	 *
	 * @type {StatusOK}
	 * @memberof AllauthClientV1AuthPasswordRequestPost200Response
	 */
	status: StatusOK;
}

/**
 * Check if a given object implements the AllauthClientV1AuthPasswordRequestPost200Response interface.
 */
export function instanceOfAllauthClientV1AuthPasswordRequestPost200Response(value: object): value is AllauthClientV1AuthPasswordRequestPost200Response {
	if (!('status' in value) || value['status'] === undefined) return false;
	return true;
}

export function AllauthClientV1AuthPasswordRequestPost200ResponseFromJSON(json: any): AllauthClientV1AuthPasswordRequestPost200Response {
	return AllauthClientV1AuthPasswordRequestPost200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthPasswordRequestPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthPasswordRequestPost200Response {
	if (json == null) {
		return json;
	}
	return {

		'status': StatusOKFromJSON(json['status'])
	};
}

export function AllauthClientV1AuthPasswordRequestPost200ResponseToJSON(value?: AllauthClientV1AuthPasswordRequestPost200Response | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': StatusOKToJSON(value['status'])
	};
}

