/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusOK } from './StatusOK';
import {
	StatusOKFromJSON,
	StatusOKFromJSONTyped,
	StatusOKToJSON
} from './StatusOK';
import type { Session } from './Session';
import {
	SessionFromJSON,
	SessionFromJSONTyped,
	SessionToJSON
} from './Session';

/**
 * 
 * @export
 * @interface AllauthClientV1SessionsGet200Response
 */
export interface AllauthClientV1SessionsGet200Response {
	/**
	 *
	 * @type {StatusOK}
	 * @memberof AllauthClientV1SessionsGet200Response
	 */
	status: StatusOK;
	/**
	 *
	 * @type {Array<Session>}
	 * @memberof AllauthClientV1SessionsGet200Response
	 */
	data: Array<Session>;
}

/**
 * Check if a given object implements the AllauthClientV1SessionsGet200Response interface.
 */
export function instanceOfAllauthClientV1SessionsGet200Response(value: object): value is AllauthClientV1SessionsGet200Response {
	if (!('status' in value) || value['status'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function AllauthClientV1SessionsGet200ResponseFromJSON(json: any): AllauthClientV1SessionsGet200Response {
	return AllauthClientV1SessionsGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1SessionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1SessionsGet200Response {
	if (json == null) {
		return json;
	}
	return {

		'status': StatusOKFromJSON(json['status']),
		'data': ((json['data'] as Array<any>).map(SessionFromJSON))
	};
}

export function AllauthClientV1SessionsGet200ResponseToJSON(value?: AllauthClientV1SessionsGet200Response | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': StatusOKToJSON(value['status']),
		'data': ((value['data'] as Array<any>).map(SessionToJSON))
	};
}

