/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface AllauthClientV1AccountEmailPutRequest
 */
export interface AllauthClientV1AccountEmailPutRequest {
	/**
	 * An email address.
	 *
	 * @type {string}
	 * @memberof AllauthClientV1AccountEmailPutRequest
	 */
	email: string;
}

/**
 * Check if a given object implements the AllauthClientV1AccountEmailPutRequest interface.
 */
export function instanceOfAllauthClientV1AccountEmailPutRequest(value: object): value is AllauthClientV1AccountEmailPutRequest {
	if (!('email' in value) || value['email'] === undefined) return false;
	return true;
}

export function AllauthClientV1AccountEmailPutRequestFromJSON(json: any): AllauthClientV1AccountEmailPutRequest {
	return AllauthClientV1AccountEmailPutRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountEmailPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountEmailPutRequest {
	if (json == null) {
		return json;
	}
	return {

		'email': json['email']
	};
}

export function AllauthClientV1AccountEmailPutRequestToJSON(value?: AllauthClientV1AccountEmailPutRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'email': value['email']
	};
}

