/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsTotpPostRequest
 */
export interface AllauthClientV1AccountAuthenticatorsTotpPostRequest {
	/**
	 * An authenticator code.
	 *
	 * @type {string}
	 * @memberof AllauthClientV1AccountAuthenticatorsTotpPostRequest
	 */
	code: string;
}

/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsTotpPostRequest interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsTotpPostRequest(value: object): value is AllauthClientV1AccountAuthenticatorsTotpPostRequest {
	if (!('code' in value) || value['code'] === undefined) return false;
	return true;
}

export function AllauthClientV1AccountAuthenticatorsTotpPostRequestFromJSON(json: any): AllauthClientV1AccountAuthenticatorsTotpPostRequest {
	return AllauthClientV1AccountAuthenticatorsTotpPostRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsTotpPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsTotpPostRequest {
	if (json == null) {
		return json;
	}
	return {

		'code': json['code']
	};
}

export function AllauthClientV1AccountAuthenticatorsTotpPostRequestToJSON(value?: AllauthClientV1AccountAuthenticatorsTotpPostRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'code': value['code']
	};
}

