/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type {
	AllauthClientV1AuthPasswordResetGet200ResponseData
} from './AllauthClientV1AuthPasswordResetGet200ResponseData';
import {
	AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSON,
	AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSONTyped,
	AllauthClientV1AuthPasswordResetGet200ResponseDataToJSON
} from './AllauthClientV1AuthPasswordResetGet200ResponseData';
import type { StatusOK } from './StatusOK';
import {
	StatusOKFromJSON,
	StatusOKFromJSONTyped,
	StatusOKToJSON
} from './StatusOK';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthPasswordResetGet200Response
 */
export interface AllauthClientV1AuthPasswordResetGet200Response {
	/**
	 *
	 * @type {StatusOK}
	 * @memberof AllauthClientV1AuthPasswordResetGet200Response
	 */
	status: StatusOK;
	/**
	 *
	 * @type {AllauthClientV1AuthPasswordResetGet200ResponseData}
	 * @memberof AllauthClientV1AuthPasswordResetGet200Response
	 */
	data: AllauthClientV1AuthPasswordResetGet200ResponseData;
}

/**
 * Check if a given object implements the AllauthClientV1AuthPasswordResetGet200Response interface.
 */
export function instanceOfAllauthClientV1AuthPasswordResetGet200Response(value: object): value is AllauthClientV1AuthPasswordResetGet200Response {
	if (!('status' in value) || value['status'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function AllauthClientV1AuthPasswordResetGet200ResponseFromJSON(json: any): AllauthClientV1AuthPasswordResetGet200Response {
	return AllauthClientV1AuthPasswordResetGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthPasswordResetGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthPasswordResetGet200Response {
	if (json == null) {
		return json;
	}
	return {

		'status': StatusOKFromJSON(json['status']),
		'data': AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSON(json['data'])
	};
}

export function AllauthClientV1AuthPasswordResetGet200ResponseToJSON(value?: AllauthClientV1AuthPasswordResetGet200Response | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': StatusOKToJSON(value['status']),
		'data': AllauthClientV1AuthPasswordResetGet200ResponseDataToJSON(value['data'])
	};
}

