/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StatusOK } from './StatusOK';
import { StatusOKFromJSON, StatusOKToJSON } from './StatusOK';
import type { EmailAddress } from './EmailAddress';
import { EmailAddressFromJSON, EmailAddressToJSON } from './EmailAddress';

/**
 *
 * @export
 * @interface AllauthClientV1AccountEmailGet200Response
 */
export interface AllauthClientV1AccountEmailGet200Response {
	/**
	 *
	 * @type {StatusOK}
	 * @memberof AllauthClientV1AccountEmailGet200Response
	 */
	status: StatusOK;
	/**
	 *
	 * @type {Array<EmailAddress>}
	 * @memberof AllauthClientV1AccountEmailGet200Response
	 */
	data: Array<EmailAddress>;
}

/**
 * Check if a given object implements the AllauthClientV1AccountEmailGet200Response interface.
 */
export function instanceOfAllauthClientV1AccountEmailGet200Response(value: object): value is AllauthClientV1AccountEmailGet200Response {
	if (!('status' in value) || value['status'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function AllauthClientV1AccountEmailGet200ResponseFromJSON(json: any): AllauthClientV1AccountEmailGet200Response {
	return AllauthClientV1AccountEmailGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AccountEmailGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountEmailGet200Response {
	if (json == null) {
		return json;
	}
	return {

		'status': StatusOKFromJSON(json['status']),
		'data': ((json['data'] as Array<any>).map(EmailAddressFromJSON))
	};
}

export function AllauthClientV1AccountEmailGet200ResponseToJSON(value?: AllauthClientV1AccountEmailGet200Response | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': StatusOKToJSON(value['status']),
		'data': ((value['data'] as Array<any>).map(EmailAddressToJSON))
	};
}

