/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { User } from './User';
import { UserFromJSON, UserToJSON } from './User';

/**
 *
 * @export
 * @interface AllauthClientV1AuthPasswordResetGet200ResponseData
 */
export interface AllauthClientV1AuthPasswordResetGet200ResponseData {
	/**
	 *
	 * @type {User}
	 * @memberof AllauthClientV1AuthPasswordResetGet200ResponseData
	 */
	user?: User;
}

/**
 * Check if a given object implements the AllauthClientV1AuthPasswordResetGet200ResponseData interface.
 */
export function instanceOfAllauthClientV1AuthPasswordResetGet200ResponseData(value: object): value is AllauthClientV1AuthPasswordResetGet200ResponseData {
	return true;
}

export function AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSON(json: any): AllauthClientV1AuthPasswordResetGet200ResponseData {
	return AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSONTyped(json, false);
}

export function AllauthClientV1AuthPasswordResetGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthPasswordResetGet200ResponseData {
	if (json == null) {
		return json;
	}
	return {

		'user': json['user'] == null ? undefined : UserFromJSON(json['user'])
	};
}

export function AllauthClientV1AuthPasswordResetGet200ResponseDataToJSON(value?: AllauthClientV1AuthPasswordResetGet200ResponseData | null): any {
	if (value == null) {
		return value;
	}
	return {

		'user': UserToJSON(value['user'])
	};
}

