/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountProvidersDeleteRequest
 */
export interface AllauthClientV1AccountProvidersDeleteRequest {
	/**
	 * The provider ID.
	 *
	 * @type {string}
	 * @memberof AllauthClientV1AccountProvidersDeleteRequest
	 */
	provider: string;
	/**
	 * The provider specific account ID.
	 *
	 * @type {string}
	 * @memberof AllauthClientV1AccountProvidersDeleteRequest
	 */
	account: string;
}

/**
 * Check if a given object implements the AllauthClientV1AccountProvidersDeleteRequest interface.
 */
export function instanceOfAllauthClientV1AccountProvidersDeleteRequest(value: object): value is AllauthClientV1AccountProvidersDeleteRequest {
	if (!('provider' in value) || value['provider'] === undefined) return false;
	if (!('account' in value) || value['account'] === undefined) return false;
	return true;
}

export function AllauthClientV1AccountProvidersDeleteRequestFromJSON(json: any): AllauthClientV1AccountProvidersDeleteRequest {
	return AllauthClientV1AccountProvidersDeleteRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountProvidersDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountProvidersDeleteRequest {
	if (json == null) {
		return json;
	}
	return {

		'provider': json['provider'],
		'account': json['account']
	};
}

export function AllauthClientV1AccountProvidersDeleteRequestToJSON(value?: AllauthClientV1AccountProvidersDeleteRequest | null): any {
	if (value == null) {
		return value;
	}
	return {

		'provider': value['provider'],
		'account': value['account']
	};
}

