/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthenticatedByThirdPartyProvider } from './AuthenticatedByThirdPartyProvider';
import {
	instanceOfAuthenticatedByThirdPartyProvider,
	AuthenticatedByThirdPartyProviderFromJSON,
	AuthenticatedByThirdPartyProviderFromJSONTyped,
	AuthenticatedByThirdPartyProviderToJSON
} from './AuthenticatedByThirdPartyProvider';
import type { AuthenticatedByUsernameEmailLogin } from './AuthenticatedByUsernameEmailLogin';
import {
	instanceOfAuthenticatedByUsernameEmailLogin,
	AuthenticatedByUsernameEmailLoginFromJSON,
	AuthenticatedByUsernameEmailLoginFromJSONTyped,
	AuthenticatedByUsernameEmailLoginToJSON
} from './AuthenticatedByUsernameEmailLogin';
import type { ReAuthenticatedBy2FA } from './ReAuthenticatedBy2FA';
import {
	instanceOfReAuthenticatedBy2FA,
	ReAuthenticatedBy2FAFromJSON,
	ReAuthenticatedBy2FAFromJSONTyped,
	ReAuthenticatedBy2FAToJSON
} from './ReAuthenticatedBy2FA';
import type { ReauthenticatedByPassword } from './ReauthenticatedByPassword';
import {
	instanceOfReauthenticatedByPassword,
	ReauthenticatedByPasswordFromJSON,
	ReauthenticatedByPasswordFromJSONTyped,
	ReauthenticatedByPasswordToJSON
} from './ReauthenticatedByPassword';

/**
 * @type AuthenticationMethod
 * 
 * @export
 */
export type AuthenticationMethod =
	AuthenticatedByThirdPartyProvider
	| AuthenticatedByUsernameEmailLogin
	| ReAuthenticatedBy2FA
	| ReauthenticatedByPassword;

export function AuthenticationMethodFromJSON(json: any): AuthenticationMethod {
	return AuthenticationMethodFromJSONTyped(json, false);
}

export function AuthenticationMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationMethod {
	if (json == null) {
		return json;
	}
	if (instanceOfAuthenticatedByThirdPartyProvider(json)) {
		return AuthenticatedByThirdPartyProviderFromJSONTyped(json, true);
	}
	if (instanceOfAuthenticatedByUsernameEmailLogin(json)) {
		return AuthenticatedByUsernameEmailLoginFromJSONTyped(json, true);
	}
	if (instanceOfReAuthenticatedBy2FA(json)) {
		return ReAuthenticatedBy2FAFromJSONTyped(json, true);
	}
	if (instanceOfReauthenticatedByPassword(json)) {
		return ReauthenticatedByPasswordFromJSONTyped(json, true);
	}
}

export function AuthenticationMethodToJSON(value?: AuthenticationMethod | null): any {
	if (value == null) {
		return value;
	}

	if (instanceOfAuthenticatedByThirdPartyProvider(value)) {
		return AuthenticatedByThirdPartyProviderToJSON(value as AuthenticatedByThirdPartyProvider);
	}
	if (instanceOfAuthenticatedByUsernameEmailLogin(value)) {
		return AuthenticatedByUsernameEmailLoginToJSON(value as AuthenticatedByUsernameEmailLogin);
	}
	if (instanceOfReAuthenticatedBy2FA(value)) {
		return ReAuthenticatedBy2FAToJSON(value as ReAuthenticatedBy2FA);
	}
	if (instanceOfReauthenticatedByPassword(value)) {
		return ReauthenticatedByPasswordToJSON(value as ReauthenticatedByPassword);
	}

	return {};
}

