/* tslint:disable */
/* eslint-disable */

/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthenticatedMeta
 */
export interface AuthenticatedMeta {
	/**
	 * The session token (`app` clients only).
	 *
	 * @type {string}
	 * @memberof AuthenticatedMeta
	 */
	sessionToken?: string;
	/**
	 * The access token (`app` clients only).
	 *
	 * @type {string}
	 * @memberof AuthenticatedMeta
	 */
	accessToken?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AuthenticatedMeta
	 */
	isAuthenticated: boolean;
}

/**
 * Check if a given object implements the AuthenticatedMeta interface.
 */
export function instanceOfAuthenticatedMeta(value: object): value is AuthenticatedMeta {
	if (!('isAuthenticated' in value) || value['isAuthenticated'] === undefined) return false;
	return true;
}

export function AuthenticatedMetaFromJSON(json: any): AuthenticatedMeta {
	return AuthenticatedMetaFromJSONTyped(json, false);
}

export function AuthenticatedMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedMeta {
	if (json == null) {
		return json;
	}
	return {

		'sessionToken': json['session_token'] == null ? undefined : json['session_token'],
		'accessToken': json['access_token'] == null ? undefined : json['access_token'],
		'isAuthenticated': json['is_authenticated']
	};
}

export function AuthenticatedMetaToJSON(value?: AuthenticatedMeta | null): any {
	if (value == null) {
		return value;
	}
	return {

		'session_token': value['sessionToken'],
		'access_token': value['accessToken'],
		'is_authenticated': value['isAuthenticated']
	};
}

