/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthenticatedByUsernameEmailLogin
 */
export interface AuthenticatedByUsernameEmailLogin {
	/**
	 *
	 * @type {string}
	 * @memberof AuthenticatedByUsernameEmailLogin
	 */
	method: AuthenticatedByUsernameEmailLoginMethodEnum;
	/**
	 * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
	 *
	 * @type {number}
	 * @memberof AuthenticatedByUsernameEmailLogin
	 */
	at: number;
	/**
	 * The email address.
	 *
	 * @type {string}
	 * @memberof AuthenticatedByUsernameEmailLogin
	 */
	email?: string;
	/**
	 * The username.
	 *
	 * @type {string}
	 * @memberof AuthenticatedByUsernameEmailLogin
	 */
	username?: string;
}


/**
 * @export
 */
export const AuthenticatedByUsernameEmailLoginMethodEnum = {
	Password: 'password'
} as const;
export type AuthenticatedByUsernameEmailLoginMethodEnum = typeof AuthenticatedByUsernameEmailLoginMethodEnum[keyof typeof AuthenticatedByUsernameEmailLoginMethodEnum];


/**
 * Check if a given object implements the AuthenticatedByUsernameEmailLogin interface.
 */
export function instanceOfAuthenticatedByUsernameEmailLogin(value: object): value is AuthenticatedByUsernameEmailLogin {
	if (!('method' in value) || value['method'] === undefined) return false;
	if (!('at' in value) || value['at'] === undefined) return false;
	return true;
}

export function AuthenticatedByUsernameEmailLoginFromJSON(json: any): AuthenticatedByUsernameEmailLogin {
	return AuthenticatedByUsernameEmailLoginFromJSONTyped(json, false);
}

export function AuthenticatedByUsernameEmailLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedByUsernameEmailLogin {
	if (json == null) {
		return json;
	}
	return {

		'method': json['method'],
		'at': json['at'],
		'email': json['email'] == null ? undefined : json['email'],
		'username': json['username'] == null ? undefined : json['username']
	};
}

export function AuthenticatedByUsernameEmailLoginToJSON(value?: AuthenticatedByUsernameEmailLogin | null): any {
	if (value == null) {
		return value;
	}
	return {

		'method': value['method'],
		'at': value['at'],
		'email': value['email'],
		'username': value['username']
	};
}

