/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticatedByThirdPartyProvider
 */
export interface AuthenticatedByThirdPartyProvider {
	/**
	 *
	 * @type {string}
	 * @memberof AuthenticatedByThirdPartyProvider
	 */
	method: AuthenticatedByThirdPartyProviderMethodEnum;
	/**
	 * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
	 *
	 * @type {number}
	 * @memberof AuthenticatedByThirdPartyProvider
	 */
	at: number;
	/**
	 * The provider ID.
	 *
	 * @type {string}
	 * @memberof AuthenticatedByThirdPartyProvider
	 */
	provider: string;
	/**
	 * The provider specific account ID.
	 *
	 * @type {string}
	 * @memberof AuthenticatedByThirdPartyProvider
	 */
	uid: string;
}


/**
 * @export
 */
export const AuthenticatedByThirdPartyProviderMethodEnum = {
	Socialaccount: 'socialaccount'
} as const;
export type AuthenticatedByThirdPartyProviderMethodEnum = typeof AuthenticatedByThirdPartyProviderMethodEnum[keyof typeof AuthenticatedByThirdPartyProviderMethodEnum];


/**
 * Check if a given object implements the AuthenticatedByThirdPartyProvider interface.
 */
export function instanceOfAuthenticatedByThirdPartyProvider(value: object): value is AuthenticatedByThirdPartyProvider {
	if (!('method' in value) || value['method'] === undefined) return false;
	if (!('at' in value) || value['at'] === undefined) return false;
	if (!('provider' in value) || value['provider'] === undefined) return false;
	if (!('uid' in value) || value['uid'] === undefined) return false;
	return true;
}

export function AuthenticatedByThirdPartyProviderFromJSON(json: any): AuthenticatedByThirdPartyProvider {
	return AuthenticatedByThirdPartyProviderFromJSONTyped(json, false);
}

export function AuthenticatedByThirdPartyProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedByThirdPartyProvider {
	if (json == null) {
		return json;
	}
	return {

		'method': json['method'],
		'at': json['at'],
		'provider': json['provider'],
		'uid': json['uid']
	};
}

export function AuthenticatedByThirdPartyProviderToJSON(value?: AuthenticatedByThirdPartyProvider | null): any {
	if (value == null) {
		return value;
	}
	return {

		'method': value['method'],
		'at': value['at'],
		'provider': value['provider'],
		'uid': value['uid']
	};
}

