/* tslint:disable */
/* eslint-disable */

/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BaseAuthenticationMeta
 */
export interface BaseAuthenticationMeta {
	/**
	 * The session token (`app` clients only).
	 *
	 * @type {string}
	 * @memberof BaseAuthenticationMeta
	 */
	sessionToken?: string;
	/**
	 * The access token (`app` clients only).
	 *
	 * @type {string}
	 * @memberof BaseAuthenticationMeta
	 */
	accessToken?: string;
}

/**
 * Check if a given object implements the BaseAuthenticationMeta interface.
 */
export function instanceOfBaseAuthenticationMeta(value: object): value is BaseAuthenticationMeta {
	return true;
}

export function BaseAuthenticationMetaFromJSON(json: any): BaseAuthenticationMeta {
	return BaseAuthenticationMetaFromJSONTyped(json, false);
}

export function BaseAuthenticationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseAuthenticationMeta {
	if (json == null) {
		return json;
	}
	return {

		'sessionToken': json['session_token'] == null ? undefined : json['session_token'],
		'accessToken': json['access_token'] == null ? undefined : json['access_token']
	};
}

export function BaseAuthenticationMetaToJSON(value?: BaseAuthenticationMeta | null): any {
	if (value == null) {
		return value;
	}
	return {

		'session_token': value['sessionToken'],
		'access_token': value['accessToken']
	};
}

