/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface ConfirmLoginCode
 */
export interface ConfirmLoginCode {
	/**
	 * An one-time code.
	 *
	 * @type {string}
	 * @memberof ConfirmLoginCode
	 */
	code: string;
}

/**
 * Check if a given object implements the ConfirmLoginCode interface.
 */
export function instanceOfConfirmLoginCode(value: object): value is ConfirmLoginCode {
	if (!('code' in value) || value['code'] === undefined) return false;
	return true;
}

export function ConfirmLoginCodeFromJSON(json: any): ConfirmLoginCode {
	return ConfirmLoginCodeFromJSONTyped(json, false);
}

export function ConfirmLoginCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmLoginCode {
	if (json == null) {
		return json;
	}
	return {

		'code': json['code']
	};
}

export function ConfirmLoginCodeToJSON(value?: ConfirmLoginCode | null): any {
	if (value == null) {
		return value;
	}
	return {

		'code': value['code']
	};
}

