/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UserSessionsConfiguration } from './UserSessionsConfiguration';
import { UserSessionsConfigurationFromJSON, UserSessionsConfigurationToJSON } from './UserSessionsConfiguration';
import type { AccountConfiguration } from './AccountConfiguration';
import { AccountConfigurationFromJSON, AccountConfigurationToJSON } from './AccountConfiguration';
import type { SocialAccountConfiguration } from './SocialAccountConfiguration';
import { SocialAccountConfigurationFromJSON, SocialAccountConfigurationToJSON } from './SocialAccountConfiguration';
import type { MFAConfiguration } from './MFAConfiguration';
import { MFAConfigurationFromJSON, MFAConfigurationToJSON } from './MFAConfiguration';

/**
 *
 * @export
 * @interface ConfigurationResponseData
 */
export interface ConfigurationResponseData {
	/**
	 *
	 * @type {AccountConfiguration}
	 * @memberof ConfigurationResponseData
	 */
	account: AccountConfiguration;
	/**
	 *
	 * @type {SocialAccountConfiguration}
	 * @memberof ConfigurationResponseData
	 */
	socialaccount?: SocialAccountConfiguration;
	/**
	 *
	 * @type {MFAConfiguration}
	 * @memberof ConfigurationResponseData
	 */
	mfa?: MFAConfiguration;
	/**
	 *
	 * @type {UserSessionsConfiguration}
	 * @memberof ConfigurationResponseData
	 */
	usersessions?: UserSessionsConfiguration;
}

/**
 * Check if a given object implements the ConfigurationResponseData interface.
 */
export function instanceOfConfigurationResponseData(value: object): value is ConfigurationResponseData {
	if (!('account' in value) || value['account'] === undefined) return false;
	return true;
}

export function ConfigurationResponseDataFromJSON(json: any): ConfigurationResponseData {
	return ConfigurationResponseDataFromJSONTyped(json, false);
}

export function ConfigurationResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationResponseData {
	if (json == null) {
		return json;
	}
	return {

		'account': AccountConfigurationFromJSON(json['account']),
		'socialaccount': json['socialaccount'] == null ? undefined : SocialAccountConfigurationFromJSON(json['socialaccount']),
		'mfa': json['mfa'] == null ? undefined : MFAConfigurationFromJSON(json['mfa']),
		'usersessions': json['usersessions'] == null ? undefined : UserSessionsConfigurationFromJSON(json['usersessions'])
	};
}

export function ConfigurationResponseDataToJSON(value?: ConfigurationResponseData | null): any {
	if (value == null) {
		return value;
	}
	return {

		'account': AccountConfigurationToJSON(value['account']),
		'socialaccount': SocialAccountConfigurationToJSON(value['socialaccount']),
		'mfa': MFAConfigurationToJSON(value['mfa']),
		'usersessions': UserSessionsConfigurationToJSON(value['usersessions'])
	};
}

