/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConflictResponse
 */
export interface ConflictResponse {
	/**
	 *
	 * @type {number}
	 * @memberof ConflictResponse
	 */
	status: ConflictResponseStatusEnum;
}


/**
 * @export
 */
export const ConflictResponseStatusEnum = {
	NUMBER_409: 409
} as const;
export type ConflictResponseStatusEnum = typeof ConflictResponseStatusEnum[keyof typeof ConflictResponseStatusEnum];


/**
 * Check if a given object implements the ConflictResponse interface.
 */
export function instanceOfConflictResponse(value: object): value is ConflictResponse {
	if (!('status' in value) || value['status'] === undefined) return false;
	return true;
}

export function ConflictResponseFromJSON(json: any): ConflictResponse {
	return ConflictResponseFromJSONTyped(json, false);
}

export function ConflictResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictResponse {
	if (json == null) {
		return json;
	}
	return {

		'status': json['status']
	};
}

export function ConflictResponseToJSON(value?: ConflictResponse | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': value['status']
	};
}

