/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface EmailVerificationInfoMeta
 */
export interface EmailVerificationInfoMeta {
	/**
	 *
	 * @type {boolean}
	 * @memberof EmailVerificationInfoMeta
	 */
	isAuthenticating: boolean;
}

/**
 * Check if a given object implements the EmailVerificationInfoMeta interface.
 */
export function instanceOfEmailVerificationInfoMeta(value: object): value is EmailVerificationInfoMeta {
	if (!('isAuthenticating' in value) || value['isAuthenticating'] === undefined) return false;
	return true;
}

export function EmailVerificationInfoMetaFromJSON(json: any): EmailVerificationInfoMeta {
	return EmailVerificationInfoMetaFromJSONTyped(json, false);
}

export function EmailVerificationInfoMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationInfoMeta {
	if (json == null) {
		return json;
	}
	return {

		'isAuthenticating': json['is_authenticating']
	};
}

export function EmailVerificationInfoMetaToJSON(value?: EmailVerificationInfoMeta | null): any {
	if (value == null) {
		return value;
	}
	return {

		'is_authenticating': value['isAuthenticating']
	};
}

