/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailVerificationInfoMeta } from './EmailVerificationInfoMeta';
import {
	EmailVerificationInfoMetaFromJSON,
	EmailVerificationInfoMetaFromJSONTyped,
	EmailVerificationInfoMetaToJSON
} from './EmailVerificationInfoMeta';
import type { EmailVerificationInfoData } from './EmailVerificationInfoData';
import {
	EmailVerificationInfoDataFromJSON,
	EmailVerificationInfoDataFromJSONTyped,
	EmailVerificationInfoDataToJSON
} from './EmailVerificationInfoData';
import type { StatusOK } from './StatusOK';
import {
	StatusOKFromJSON,
	StatusOKFromJSONTyped,
	StatusOKToJSON
} from './StatusOK';

/**
 *
 * @export
 * @interface EmailVerificationInfo
 */
export interface EmailVerificationInfo {
	/**
	 *
	 * @type {StatusOK}
	 * @memberof EmailVerificationInfo
	 */
	status: StatusOK;
	/**
	 *
	 * @type {EmailVerificationInfoData}
	 * @memberof EmailVerificationInfo
	 */
	data: EmailVerificationInfoData;
	/**
	 *
	 * @type {EmailVerificationInfoMeta}
	 * @memberof EmailVerificationInfo
	 */
	meta: EmailVerificationInfoMeta;
}

/**
 * Check if a given object implements the EmailVerificationInfo interface.
 */
export function instanceOfEmailVerificationInfo(value: object): value is EmailVerificationInfo {
	if (!('status' in value) || value['status'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	if (!('meta' in value) || value['meta'] === undefined) return false;
	return true;
}

export function EmailVerificationInfoFromJSON(json: any): EmailVerificationInfo {
	return EmailVerificationInfoFromJSONTyped(json, false);
}

export function EmailVerificationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationInfo {
	if (json == null) {
		return json;
	}
	return {

		'status': StatusOKFromJSON(json['status']),
		'data': EmailVerificationInfoDataFromJSON(json['data']),
		'meta': EmailVerificationInfoMetaFromJSON(json['meta'])
	};
}

export function EmailVerificationInfoToJSON(value?: EmailVerificationInfo | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': StatusOKToJSON(value['status']),
		'data': EmailVerificationInfoDataToJSON(value['data']),
		'meta': EmailVerificationInfoMetaToJSON(value['meta'])
	};
}

