/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EmailAddress
 */
export interface EmailAddress {
	/**
	 * The email address.
	 *
	 * @type {string}
	 * @memberof EmailAddress
	 */
	email: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof EmailAddress
	 */
	primary: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof EmailAddress
	 */
	verified: boolean;
}

/**
 * Check if a given object implements the EmailAddress interface.
 */
export function instanceOfEmailAddress(value: object): value is EmailAddress {
	if (!('email' in value) || value['email'] === undefined) return false;
	if (!('primary' in value) || value['primary'] === undefined) return false;
	if (!('verified' in value) || value['verified'] === undefined) return false;
	return true;
}

export function EmailAddressFromJSON(json: any): EmailAddress {
	return EmailAddressFromJSONTyped(json, false);
}

export function EmailAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAddress {
	if (json == null) {
		return json;
	}
	return {

		'email': json['email'],
		'primary': json['primary'],
		'verified': json['verified']
	};
}

export function EmailAddressToJSON(value?: EmailAddress | null): any {
	if (value == null) {
		return value;
	}
	return {

		'email': value['email'],
		'primary': value['primary'],
		'verified': value['verified']
	};
}

