/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
	UserFromJSON,
	UserFromJSONTyped,
	UserToJSON
} from './User';

/**
 *
 * @export
 * @interface EmailVerificationInfoData
 */
export interface EmailVerificationInfoData {
	/**
	 * The email address.
	 *
	 * @type {string}
	 * @memberof EmailVerificationInfoData
	 */
	email: string;
	/**
	 *
	 * @type {User}
	 * @memberof EmailVerificationInfoData
	 */
	user: User;
}

/**
 * Check if a given object implements the EmailVerificationInfoData interface.
 */
export function instanceOfEmailVerificationInfoData(value: object): value is EmailVerificationInfoData {
	if (!('email' in value) || value['email'] === undefined) return false;
	if (!('user' in value) || value['user'] === undefined) return false;
	return true;
}

export function EmailVerificationInfoDataFromJSON(json: any): EmailVerificationInfoData {
	return EmailVerificationInfoDataFromJSONTyped(json, false);
}

export function EmailVerificationInfoDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationInfoData {
	if (json == null) {
		return json;
	}
	return {

		'email': json['email'],
		'user': UserFromJSON(json['user'])
	};
}

export function EmailVerificationInfoDataToJSON(value?: EmailVerificationInfoData | null): any {
	if (value == null) {
		return value;
	}
	return {

		'email': value['email'],
		'user': UserToJSON(value['user'])
	};
}

