/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForbiddenResponse
 */
export interface ForbiddenResponse {
	/**
	 *
	 * @type {number}
	 * @memberof ForbiddenResponse
	 */
	status: ForbiddenResponseStatusEnum;
}


/**
 * @export
 */
export const ForbiddenResponseStatusEnum = {
	NUMBER_403: 403
} as const;
export type ForbiddenResponseStatusEnum = typeof ForbiddenResponseStatusEnum[keyof typeof ForbiddenResponseStatusEnum];


/**
 * Check if a given object implements the ForbiddenResponse interface.
 */
export function instanceOfForbiddenResponse(value: object): value is ForbiddenResponse {
	if (!('status' in value) || value['status'] === undefined) return false;
	return true;
}

export function ForbiddenResponseFromJSON(json: any): ForbiddenResponse {
	return ForbiddenResponseFromJSONTyped(json, false);
}

export function ForbiddenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenResponse {
	if (json == null) {
		return json;
	}
	return {

		'status': json['status']
	};
}

export function ForbiddenResponseToJSON(value?: ForbiddenResponse | null): any {
	if (value == null) {
		return value;
	}
	return {

		'status': value['status']
	};
}

