/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Login
 */
export interface Login {
	/**
	 * The password.
	 *
	 * @type {string}
	 * @memberof Login
	 */
	password: string;
	/**
	 * The username.
	 *
	 * @type {string}
	 * @memberof Login
	 */
	username: string;
}

/**
 * Check if a given object implements the Login interface.
 */
export function instanceOfLogin(value: object): value is Login {
	if (!('password' in value) || value['password'] === undefined) return false;
	if (!('username' in value) || value['username'] === undefined) return false;
	return true;
}

export function LoginFromJSON(json: any): Login {
	return LoginFromJSONTyped(json, false);
}

export function LoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login {
	if (json == null) {
		return json;
	}
	return {

		'password': json['password'],
		'username': json['username']
	};
}

export function LoginToJSON(value?: Login | null): any {
	if (value == null) {
		return value;
	}
	return {

		'password': value['password'],
		'username': value['username']
	};
}

