/* tslint:disable */
/* eslint-disable */

/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MFAAuthenticate
 */
export interface MFAAuthenticate {
	/**
	 * An authenticator code.
	 *
	 * @type {string}
	 * @memberof MFAAuthenticate
	 */
	code: string;
}

/**
 * Check if a given object implements the MFAAuthenticate interface.
 */
export function instanceOfMFAAuthenticate(value: object): value is MFAAuthenticate {
	if (!('code' in value) || value['code'] === undefined) return false;
	return true;
}

export function MFAAuthenticateFromJSON(json: any): MFAAuthenticate {
	return MFAAuthenticateFromJSONTyped(json, false);
}

export function MFAAuthenticateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MFAAuthenticate {
	if (json == null) {
		return json;
	}
	return {

		'code': json['code']
	};
}

export function MFAAuthenticateToJSON(value?: MFAAuthenticate | null): any {
	if (value == null) {
		return value;
	}
	return {

		'code': value['code']
	};
}

