/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface ProviderSignup
 */
export interface ProviderSignup {
	/**
	 * The email address.
	 *
	 * @type {string}
	 * @memberof ProviderSignup
	 */
	email: string;
}

/**
 * Check if a given object implements the ProviderSignup interface.
 */
export function instanceOfProviderSignup(value: object): value is ProviderSignup {
	if (!('email' in value) || value['email'] === undefined) return false;
	return true;
}

export function ProviderSignupFromJSON(json: any): ProviderSignup {
	return ProviderSignupFromJSONTyped(json, false);
}

export function ProviderSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderSignup {
	if (json == null) {
		return json;
	}
	return {

		'email': json['email']
	};
}

export function ProviderSignupToJSON(value?: ProviderSignup | null): any {
	if (value == null) {
		return value;
	}
	return {

		'email': value['email']
	};
}

