/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Provider } from './Provider';
import { ProviderFromJSON, ProviderToJSON } from './Provider';

/**
 *
 * @export
 * @interface ProviderAccount
 */
export interface ProviderAccount {
	/**
	 * The provider specific account ID.
	 *
	 * @type {string}
	 * @memberof ProviderAccount
	 */
	uid: string;
	/**
	 * A name derived from the third-party provider account data.
	 *
	 * @type {string}
	 * @memberof ProviderAccount
	 */
	display: string;
	/**
	 *
	 * @type {Provider}
	 * @memberof ProviderAccount
	 */
	provider: Provider;
}

/**
 * Check if a given object implements the ProviderAccount interface.
 */
export function instanceOfProviderAccount(value: object): value is ProviderAccount {
	if (!('uid' in value) || value['uid'] === undefined) return false;
	if (!('display' in value) || value['display'] === undefined) return false;
	if (!('provider' in value) || value['provider'] === undefined) return false;
	return true;
}

export function ProviderAccountFromJSON(json: any): ProviderAccount {
	return ProviderAccountFromJSONTyped(json, false);
}

export function ProviderAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderAccount {
	if (json == null) {
		return json;
	}
	return {

		'uid': json['uid'],
		'display': json['display'],
		'provider': ProviderFromJSON(json['provider'])
	};
}

export function ProviderAccountToJSON(value?: ProviderAccount | null): any {
	if (value == null) {
		return value;
	}
	return {

		'uid': value['uid'],
		'display': value['display'],
		'provider': ProviderToJSON(value['provider'])
	};
}

