/* tslint:disable */
/* eslint-disable */

/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RecoveryCodesAuthenticator
 */
export interface RecoveryCodesAuthenticator {
	/**
	 * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
	 *
	 * @type {number}
	 * @memberof RecoveryCodesAuthenticator
	 */
	lastUsedAt: number;
	/**
	 * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
	 *
	 * @type {number}
	 * @memberof RecoveryCodesAuthenticator
	 */
	createdAt: number;
	/**
	 * The authenticator type.
	 *
	 * @type {string}
	 * @memberof RecoveryCodesAuthenticator
	 */
	type: RecoveryCodesAuthenticatorTypeEnum;
	/**
	 * The total number of recovery codes that initially were available.
	 *
	 * @type {number}
	 * @memberof RecoveryCodesAuthenticator
	 */
	totalCodeCount: number;
	/**
	 * The number of recovery codes that are unused.
	 *
	 * @type {number}
	 * @memberof RecoveryCodesAuthenticator
	 */
	unusedCodeCount: number;
}


/**
 * @export
 */
export const RecoveryCodesAuthenticatorTypeEnum = {
	RecoveryCodes: 'recovery_codes'
} as const;
export type RecoveryCodesAuthenticatorTypeEnum = typeof RecoveryCodesAuthenticatorTypeEnum[keyof typeof RecoveryCodesAuthenticatorTypeEnum];


/**
 * Check if a given object implements the RecoveryCodesAuthenticator interface.
 */
export function instanceOfRecoveryCodesAuthenticator(value: object): value is RecoveryCodesAuthenticator {
	if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
	if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
	if (!('type' in value) || value['type'] === undefined) return false;
	if (!('totalCodeCount' in value) || value['totalCodeCount'] === undefined) return false;
	if (!('unusedCodeCount' in value) || value['unusedCodeCount'] === undefined) return false;
	return true;
}

export function RecoveryCodesAuthenticatorFromJSON(json: any): RecoveryCodesAuthenticator {
	return RecoveryCodesAuthenticatorFromJSONTyped(json, false);
}

export function RecoveryCodesAuthenticatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryCodesAuthenticator {
	if (json == null) {
		return json;
	}
	return {

		'lastUsedAt': json['last_used_at'],
		'createdAt': json['created_at'],
		'type': json['type'],
		'totalCodeCount': json['total_code_count'],
		'unusedCodeCount': json['unused_code_count']
	};
}

export function RecoveryCodesAuthenticatorToJSON(value?: RecoveryCodesAuthenticator | null): any {
	if (value == null) {
		return value;
	}
	return {

		'last_used_at': value['lastUsedAt'],
		'created_at': value['createdAt'],
		'type': value['type'],
		'total_code_count': value['totalCodeCount'],
		'unused_code_count': value['unusedCodeCount']
	};
}

