/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPassword
 */
export interface RequestPassword {
	/**
	 * The email address.
	 *
	 * @type {string}
	 * @memberof RequestPassword
	 */
	email: string;
}

/**
 * Check if a given object implements the RequestPassword interface.
 */
export function instanceOfRequestPassword(value: object): value is RequestPassword {
	if (!('email' in value) || value['email'] === undefined) return false;
	return true;
}

export function RequestPasswordFromJSON(json: any): RequestPassword {
	return RequestPasswordFromJSONTyped(json, false);
}

export function RequestPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPassword {
	if (json == null) {
		return json;
	}
	return {

		'email': json['email']
	};
}

export function RequestPasswordToJSON(value?: RequestPassword | null): any {
	if (value == null) {
		return value;
	}
	return {

		'email': value['email']
	};
}

