/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type UserId
 * The user ID.
 *
 * @export
 */
export type UserId = number | string;

export function UserIdFromJSON(json: any): UserId {
	return UserIdFromJSONTyped(json, false);
}

export function UserIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserId {
	if (json == null) {
		return json;
	}
	if (instanceOfnumber(json)) {
		return numberFromJSONTyped(json, true);
	}
	if (instanceOfstring(json)) {
		return stringFromJSONTyped(json, true);
	}
}

export function UserIdToJSON(value?: UserId | null): any {
	if (value == null) {
		return value;
	}

	if (instanceOfnumber(value)) {
		return numberToJSON(value as number);
	}
	if (instanceOfstring(value)) {
		return stringToJSON(value as string);
	}

	return {};
}

