/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * Configuration of the Django `allauth.usersessions` app.
 *
 * @export
 * @interface UserSessionsConfiguration
 */
export interface UserSessionsConfiguration {
	/**
	 * Matches `settings.USERSESSIONS_TRACK_ACTIVITY`.
	 *
	 * @type {boolean}
	 * @memberof UserSessionsConfiguration
	 */
	trackActivity: boolean;
}

/**
 * Check if a given object implements the UserSessionsConfiguration interface.
 */
export function instanceOfUserSessionsConfiguration(value: object): value is UserSessionsConfiguration {
	if (!('trackActivity' in value) || value['trackActivity'] === undefined) return false;
	return true;
}

export function UserSessionsConfigurationFromJSON(json: any): UserSessionsConfiguration {
	return UserSessionsConfigurationFromJSONTyped(json, false);
}

export function UserSessionsConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSessionsConfiguration {
	if (json == null) {
		return json;
	}
	return {

		'trackActivity': json['track_activity']
	};
}

export function UserSessionsConfigurationToJSON(value?: UserSessionsConfiguration | null): any {
	if (value == null) {
		return value;
	}
	return {

		'track_activity': value['trackActivity']
	};
}

