# Generated by Django 5.0.6 on 2024-06-05 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_word_word"),
        ("learning", "0004_learnedword"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="learnedword",
            constraint=models.UniqueConstraint(
                fields=("user", "word"), name="unique_word_per_user"
            ),
        ),
        migrations.AddField(
            model_name="invalidword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content.word",
                unique=True,
            ),
        ),
    ]
