# Generated by Django 5.0.6 on 2024-06-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_word_word"),
        ("learning", "0005_invalidword_learnedword_unique_word_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidword",
            name="word",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="content.word"
            ),
        ),
    ]
