# Generated by Django 5.0.7 on 2024-07-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_word_word"),
        ("learning", "0006_alter_invalidword_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrongAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="content.word"
                    ),
                ),
            ],
        ),
    ]
