# Generated by Django 5.1.4 on 2024-12-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_pokemon_content_pok_id_from_348066_idx"),
        (
            "learning",
            "0009_remove_learnedpokemonname_unique_learned_pokemon_per_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemonnameresult",
            name="expected_language",
        ),
        migrations.RemoveField(
            model_name="pokemonnameresult",
            name="given_language",
        ),
        migrations.AddField(
            model_name="pokemonnameresult",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.language",
            ),
            preserve_default=False,
        ),
    ]
