# Generated by Django 5.0.6 on 2024-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                        ],
                        max_length=100,
                    ),
                ),
                ("gender", models.CharField(max_length=10, null=True)),
                ("usage_frequency", models.IntegerField()),
            ],
        ),
    ]
