# Generated by Django 5.0.6 on 2024-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
