# Generated by Django 5.1.4 on 2024-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_language_pokemon_pokemonname"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_full_name",
            field=models.CharField(
                default="default_name_should_not_show_up", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="language_short_name",
            field=models.CharField(
                default="default_short_name_should_not_show_up", max_length=100
            ),
            preserve_default=False,
        ),
    ]
