# Generated by Django 5.1.4 on 2024-12-27 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_language_language_full_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="language_full_name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="language_short_name",
            new_name="short_name",
        ),
    ]
